workspace 'Sample.xcworkspace'
project 'Sample.xcodeproj'
platform :ios, '8.0'
use_frameworks!

plugin 'cocoapods-keys', {
    :project => "Sample",
    :keys => [
    "FWTAccessID",
    "FWTSecretKey"
]}

target :Sample do
  pod 'Notifiable', :path => '..'
  pod 'SVProgressHUD', '~> 1.1'
end
