workspace 'Sample.xcworkspace'
project 'Sample.xcodeproj'
platform :ios, '8.0'
use_frameworks!

plugin 'cocoapods-keys', {
    :project => "Sample",
    :keys => [
    "FWTAccessID",
    "FWTSecretKey"
]}

target :Sample do
  pod 'Notifiable', :path => '..'
  pod 'SVProgressHUD', '~> 1.1'
end

post_install do | installer |
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
    end
end
