workspace 'Sample.xcworkspace'
project 'Sample.xcodeproj'
platform :ios, '10.0'
use_frameworks!

def common
    plugin 'cocoapods-keys', {
        :project => "Sample",
        :keys => [
        "FWTAccessID",
        "FWTSecretKey"
        ]}
    pod 'Notifiable', :path => '..'
end

target 'Sample' do
    common
    pod 'SVProgressHUD', '~> 2.2.5'
end

target 'NotificationService' do
    common
end

post_install do | installer |
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
    end
end
